library ieee;
use ieee.std_logic_1164.all;

------------------------------------------------------------------------------
-- TOP-LEVEL SoC WRAPPER
-- Connects the ARM Processing System (PS) to the Custom Intersection IP
------------------------------------------------------------------------------
entity intersection_soc_top is
    port (
        -- =========================================================
        -- Zynq PS Hard Macro Ports (Physical Board DDR/IO)
        -- =========================================================
        DDR_addr          : inout std_logic_vector(14 downto 0);
        DDR_ba            : inout std_logic_vector(2 downto 0);
        DDR_cas_n         : inout std_logic;
        DDR_ck_n          : inout std_logic;
        DDR_ck_p          : inout std_logic;
        DDR_cke           : inout std_logic;
        DDR_cs_n          : inout std_logic;
        DDR_dm            : inout std_logic_vector(3 downto 0);
        DDR_dq            : inout std_logic_vector(31 downto 0);
        DDR_dqs_n         : inout std_logic_vector(3 downto 0);
        DDR_dqs_p         : inout std_logic_vector(3 downto 0);
        DDR_odt           : inout std_logic;
        DDR_ras_n         : inout std_logic;
        DDR_reset_n       : inout std_logic;
        DDR_we_n          : inout std_logic;
        
        FIXED_IO_ddr_vrn  : inout std_logic;
        FIXED_IO_ddr_vrp  : inout std_logic;
        FIXED_IO_mio      : inout std_logic_vector(53 downto 0);
        FIXED_IO_ps_clk   : inout std_logic;
        FIXED_IO_ps_porb  : inout std_logic;
        FIXED_IO_ps_srstb : inout std_logic
    );
end entity intersection_soc_top;

architecture structural of intersection_soc_top is

    -- =========================================================
    -- INTERNAL INTERCONNECT SIGNALS (The AXI4-Lite Bus)
    -- =========================================================
    -- Clock and Reset from the ARM PS to the FPGA Fabric
    signal ps_fclk_clk0    : std_logic;
    signal ps_fclk_reset0_n: std_logic;

    -- AXI4-Lite Write Address Channel
    signal axi_awaddr  : std_logic_vector(31 downto 0);
    signal axi_awprot  : std_logic_vector(2 downto 0);
    signal axi_awvalid : std_logic;
    signal axi_awready : std_logic;

    -- AXI4-Lite Write Data Channel
    signal axi_wdata   : std_logic_vector(31 downto 0);
    signal axi_wstrb   : std_logic_vector(3 downto 0);
    signal axi_wvalid  : std_logic;
    signal axi_wready  : std_logic;

    -- AXI4-Lite Write Response Channel
    signal axi_bresp   : std_logic_vector(1 downto 0);
    signal axi_bvalid  : std_logic;
    signal axi_bready  : std_logic;

    -- AXI4-Lite Read Address Channel
    signal axi_araddr  : std_logic_vector(31 downto 0);
    signal axi_arprot  : std_logic_vector(2 downto 0);
    signal axi_arvalid : std_logic;
    signal axi_arready : std_logic;

    -- AXI4-Lite Read Data Channel
    signal axi_rdata   : std_logic_vector(31 downto 0);
    signal axi_rresp   : std_logic_vector(1 downto 0);
    signal axi_rvalid  : std_logic;
    signal axi_rready  : std_logic;

    -- =========================================================
    -- COMPONENT DECLARATIONS
    -- =========================================================
    
    -- 1. The ARM Processing System (Generated by Vivado IP Integrator)
    component zynq_ps_wrapper is
        port (
            -- External Pins
            DDR_addr          : inout std_logic_vector(14 downto 0);
            DDR_ba            : inout std_logic_vector(2 downto 0);
            DDR_cas_n         : inout std_logic;
            DDR_ck_n          : inout std_logic;
            DDR_ck_p          : inout std_logic;
            DDR_cke           : inout std_logic;
            DDR_cs_n          : inout std_logic;
            DDR_dm            : inout std_logic_vector(3 downto 0);
            DDR_dq            : inout std_logic_vector(31 downto 0);
            DDR_dqs_n         : inout std_logic_vector(3 downto 0);
            DDR_dqs_p         : inout std_logic_vector(3 downto 0);
            DDR_odt           : inout std_logic;
            DDR_ras_n         : inout std_logic;
            DDR_reset_n       : inout std_logic;
            DDR_we_n          : inout std_logic;
            FIXED_IO_ddr_vrn  : inout std_logic;
            FIXED_IO_ddr_vrp  : inout std_logic;
            FIXED_IO_mio      : inout std_logic_vector(53 downto 0);
            FIXED_IO_ps_clk   : inout std_logic;
            FIXED_IO_ps_porb  : inout std_logic;
            FIXED_IO_ps_srstb : inout std_logic;
            
            -- Internal FPGA Fabric Clocks & Resets
            FCLK_CLK0         : out std_logic;
            FCLK_RESET0_N     : out std_logic;
            
            -- AXI Master Interface (M_AXI) connected to 0x40000000
            M_AXI_awaddr  : out std_logic_vector(31 downto 0);
            M_AXI_awprot  : out std_logic_vector(2 downto 0);
            M_AXI_awvalid : out std_logic;
            M_AXI_awready : in  std_logic;
            M_AXI_wdata   : out std_logic_vector(31 downto 0);
            M_AXI_wstrb   : out std_logic_vector(3 downto 0);
            M_AXI_wvalid  : out std_logic;
            M_AXI_wready  : in  std_logic;
            M_AXI_bresp   : in  std_logic_vector(1 downto 0);
            M_AXI_bvalid  : in  std_logic;
            M_AXI_bready  : out std_logic;
            M_AXI_araddr  : out std_logic_vector(31 downto 0);
            M_AXI_arprot  : out std_logic_vector(2 downto 0);
            M_AXI_arvalid : out std_logic;
            M_AXI_arready : in  std_logic;
            M_AXI_rdata   : in  std_logic_vector(31 downto 0);
            M_AXI_rresp   : in  std_logic_vector(1 downto 0);
            M_AXI_rvalid  : in  std_logic;
            M_AXI_rready  : out std_logic
        );
    end component;

    -- 2. Your Custom Intersection AXI-Lite Bridge
    component intersection_axi_lite_bridge is
        generic (
            C_S_AXI_DATA_WIDTH : integer := 32;
            C_S_AXI_ADDR_WIDTH : integer := 5
        );
        port (
            S_AXI_ACLK    : in std_logic;
            S_AXI_ARESETN : in std_logic;
            S_AXI_AWADDR  : in std_logic_vector(4 downto 0);
            S_AXI_AWPROT  : in std_logic_vector(2 downto 0);
            S_AXI_AWVALID : in std_logic;
            S_AXI_AWREADY : out std_logic;
            S_AXI_WDATA   : in std_logic_vector(31 downto 0);
            S_AXI_WSTRB   : in std_logic_vector(3 downto 0);
            S_AXI_WVALID  : in std_logic;
            S_AXI_WREADY  : out std_logic;
            S_AXI_BRESP   : out std_logic_vector(1 downto 0);
            S_AXI_BVALID  : out std_logic;
            S_AXI_BREADY  : in std_logic;
            S_AXI_ARADDR  : in std_logic_vector(4 downto 0);
            S_AXI_ARPROT  : in std_logic_vector(2 downto 0);
            S_AXI_ARVALID : in std_logic;
            S_AXI_ARREADY : out std_logic;
            S_AXI_RDATA   : out std_logic_vector(31 downto 0);
            S_AXI_RRESP   : out std_logic_vector(1 downto 0);
            S_AXI_RVALID  : out std_logic;
            S_AXI_RREADY  : in std_logic
        );
    end component;

begin

    -- =========================================================
    -- INSTANTIATE THE ARM PROCESSING SYSTEM (FreeRTOS Host)
    -- =========================================================
    ps_inst : zynq_ps_wrapper
        port map (
            -- Board I/O
            DDR_addr          => DDR_addr,
            DDR_ba            => DDR_ba,
            DDR_cas_n         => DDR_cas_n,
            DDR_ck_n          => DDR_ck_n,
            DDR_ck_p          => DDR_ck_p,
            DDR_cke           => DDR_cke,
            DDR_cs_n          => DDR_cs_n,
            DDR_dm            => DDR_dm,
            DDR_dq            => DDR_dq,
            DDR_dqs_n         => DDR_dqs_n,
            DDR_dqs_p         => DDR_dqs_p,
            DDR_odt           => DDR_odt,
            DDR_ras_n         => DDR_ras_n,
            DDR_reset_n       => DDR_reset_n,
            DDR_we_n          => DDR_we_n,
            FIXED_IO_ddr_vrn  => FIXED_IO_ddr_vrn,
            FIXED_IO_ddr_vrp  => FIXED_IO_ddr_vrp,
            FIXED_IO_mio      => FIXED_IO_mio,
            FIXED_IO_ps_clk   => FIXED_IO_ps_clk,
            FIXED_IO_ps_porb  => FIXED_IO_ps_porb,
            FIXED_IO_ps_srstb => FIXED_IO_ps_srstb,
            
            -- Clocks out to FPGA Fabric
            FCLK_CLK0         => ps_fclk_clk0,
            FCLK_RESET0_N     => ps_fclk_reset0_n,
            
            -- Master AXI Bus (Driven by FreeRTOS C code)
            M_AXI_awaddr  => axi_awaddr,
            M_AXI_awprot  => axi_awprot,
            M_AXI_awvalid => axi_awvalid,
            M_AXI_awready => axi_awready,
            M_AXI_wdata   => axi_wdata,
            M_AXI_wstrb   => axi_wstrb,
            M_AXI_wvalid  => axi_wvalid,
            M_AXI_wready  => axi_wready,
            M_AXI_bresp   => axi_bresp,
            M_AXI_bvalid  => axi_bvalid,
            M_AXI_bready  => axi_bready,
            M_AXI_araddr  => axi_araddr,
            M_AXI_arprot  => axi_arprot,
            M_AXI_arvalid => axi_arvalid,
            M_AXI_arready => axi_arready,
            M_AXI_rdata   => axi_rdata,
            M_AXI_rresp   => axi_rresp,
            M_AXI_rvalid  => axi_rvalid,
            M_AXI_rready  => axi_rready
        );

    -- =========================================================
    -- INSTANTIATE YOUR INTERSECTION HARDWARE ACCELERATOR
    -- =========================================================
    intersection_ip_inst : intersection_axi_lite_bridge
        generic map (
            C_S_AXI_DATA_WIDTH => 32,
            C_S_AXI_ADDR_WIDTH => 5
        )
        port map (
            -- Clock & Reset (Driven by the ARM PS)
            S_AXI_ACLK    => ps_fclk_clk0,
            S_AXI_ARESETN => ps_fclk_reset0_n,
            
            -- Slave AXI Bus (Connects to PS Master, truncating addresses to 5 bits)
            S_AXI_AWADDR  => axi_awaddr(4 downto 0),
            S_AXI_AWPROT  => axi_awprot,
            S_AXI_AWVALID => axi_awvalid,
            S_AXI_AWREADY => axi_awready,
            S_AXI_WDATA   => axi_wdata,
            S_AXI_WSTRB   => axi_wstrb,
            S_AXI_WVALID  => axi_wvalid,
            S_AXI_WREADY  => axi_wready,
            S_AXI_BRESP   => axi_bresp,
            S_AXI_BVALID  => axi_bvalid,
            S_AXI_BREADY  => axi_bready,
            S_AXI_ARADDR  => axi_araddr(4 downto 0),
            S_AXI_ARPROT  => axi_arprot,
            S_AXI_ARVALID => axi_arvalid,
            S_AXI_ARREADY => axi_arready,
            S_AXI_RDATA   => axi_rdata,
            S_AXI_RRESP   => axi_rresp,
            S_AXI_RVALID  => axi_rvalid,
            S_AXI_RREADY  => axi_rready
        );

end architecture;